### PR TITLE
Added More options for color!

### PR DESCRIPTION
**Pull request by Bwashere**

### CODE REVIEW

**Comment by Bwashere** [comment]
The edit to main.js was ment to be left out

**Comment by Itz-Hyperz** [comment]
I will merge this, but I need you to fix it to actually work...

**Comment by Bwashere** [comment]
What was wrong with it? It looked right when I did it but I also did just wake up

**Comment by Itz-Hyperz** [comment]
https://cdn.hyperz.dev/dn4aemv2.png

You didn't change the chalk colors.

**Comment by Bwashere** [comment]
grey and black was there before?

**Comment by Bwashere** [comment]
https://cdn.discordapp.com/attachments/876932681299021904/877678781396054077/unknown.png

**Comment by Itz-Hyperz** [comment]
no no no, inside of the else if statement, for example, 

```js
if (headerColor === 'cyan') {
   hcolor = chalk.cyan(head)
} else if (headerColor === 'grey') {
   hcolor = chalk.cyan(head)
} else if (headerColor === 'black') {
   hcolor = chalk.cyan(head)
}
```

notice how it will still set `hcolor` to `chalk.cyan`

that needs to be changed.

**Comment by Bwashere** [comment]
ohhh I didnt see that before I got you hold up

**Comment by Bwashere** [comment]
Done.

**Comment by Itz-Hyperz** [comment]
the rest of it looks good.

**Pull request merged**
